model:
  name: dfkde
  backbone: efficientnet_b0 # Choose the backbone model, adjust based on your needs
  pretrained: true # Use pretrained weights

dataset:
  name: dataset2 # Name of your dataset
  path: ./dataset2
  normal_dir: ./dataset2/good
  abnormal_dir: ./dataset2/crack
  class_path: anomalib.data.Folder # Adjusted class path
  image_size: 256 # Adjust based on your image dimensions
  mask_size: 256 # Typically the same as image_size for segmentation tasks

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.001

testing:
  batch_size: 1

anomaly_map:
  threshold: 1.5 # Set an initial threshold for anomaly detection

augmentation:
  enabled: true
  methods:
    - HorizontalFlip
    - VerticalFlip
    - ColorJitter
